# Generated by Django 5.0.1 on 2024-01-10 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100, null=True)),
                ('team2', models.CharField(max_length=100, null=True)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('description', models.TextField(max_length=200)),
                ('team1_image', models.ImageField(blank=True, null=True, upload_to='Profile_Images/')),
                ('team2_image', models.ImageField(blank=True, null=True, upload_to='Profile_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('Local Seat', 'Local Seat'), ('Open Stand', 'Open Stand')], max_length=20)),
                ('available_quantity', models.IntegerField()),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('stadium_image', models.ImageField(blank=True, null=True, upload_to='Profile_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField()),
                ('number_of_tickets', models.IntegerField()),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qr_scanned', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.events')),
                ('teamfixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.fixtures')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.seattype')),
            ],
        ),
        migrations.AddField(
            model_name='fixtures',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.stadium'),
        ),
        migrations.CreateModel(
            name='Athletics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('description', models.TextField(max_length=200)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='Profile_Images/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.stadium')),
            ],
        ),
    ]
